pipeline:
  publish:
    image: plugins/docker
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    repo: 2327co/drone-flynn
    tags:
    - latest
    - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    when:
      branch: master
